/*
Copyright 2024 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package controller implements the srsRAN gNB NFDeployment reconciler.
//
// Architecture: three SEPARATE pods are deployed per NFDeployment (provider=gnb.srsran.io):
//
//	CU-CP  – binds N2 (NGAP→AMF), E1 (E1AP↔CU-UP), F1C (F1-AP↔DU)
//	CU-UP  – binds N3 (GTP-U→UPF), E1 (E1AP←CU-CP), F1U (GTP-U↔DU)
//	DU     – binds F1C (F1-AP←CU-CP), F1U (GTP-U←CU-UP), ZMQ RF
//
// IPs come exclusively from NFDeployment.spec.interfaces[] populated by the
// Nephio nfdeploy-fn (2nd pass) after the generic-specializer has resolved IPAM.
package controller

import (
	"context"
	"fmt"
	"slices"
	"time"

	"github.com/go-logr/logr"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	workloadv1alpha1 "github.com/nephio-project/api/workload/v1alpha1"
	srsranov1alpha1 "workload.nephio.org/srsran_operator/api/v1alpha1"
)

// GetSupportedProviders returns the list of NFDeployment provider strings
// handled by this controller.
func GetSupportedProviders() []string {
	return []string{"gnb.srsran.io"}
}

// NfResource is the interface implemented by GnbResources.
// It matches the OAI pattern so the same CreateAll / DeleteAll helpers can be reused.
type NfResource interface {
	GetServiceAccount() []*corev1.ServiceAccount
	GetConfigMap(logr.Logger, *workloadv1alpha1.NFDeployment, *ConfigInfo) []*corev1.ConfigMap
	GetDeployment(logr.Logger, *workloadv1alpha1.NFDeployment, *ConfigInfo) []*appsv1.Deployment
	GetService() []*corev1.Service
}

// RANDeploymentReconciler reconciles NFDeployment objects with provider=gnb.srsran.io.
type RANDeploymentReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// CreateAll creates or updates all Kubernetes resources generated by nfResource in the cluster.
func (r *RANDeploymentReconciler) CreateAll(ctx context.Context, nfDeploy *workloadv1alpha1.NFDeployment, nfResource NfResource, configInfo *ConfigInfo) []error {
	logger := log.FromContext(ctx).WithValues("NFDeployment", types.NamespacedName{Namespace: nfDeploy.Namespace, Name: nfDeploy.Name})
	var errs []error
	ns := nfDeploy.Namespace

	for _, sa := range nfResource.GetServiceAccount() {
		if sa.Namespace == "" {
			sa.Namespace = ns
		}
		if err := r.Create(ctx, sa); err != nil && !errors.IsAlreadyExists(err) {
			errs = append(errs, err)
			logger.Error(err, "Error creating ServiceAccount")
		}
	}
	for _, cm := range nfResource.GetConfigMap(logger, nfDeploy, configInfo) {
		if cm == nil {
			continue
		}
		if cm.Namespace == "" {
			cm.Namespace = ns
		}
		existing := cm.DeepCopy()
		_, err := controllerutil.CreateOrUpdate(ctx, r.Client, existing, func() error {
			existing.Data = cm.Data
			return nil
		})
		if err != nil {
			errs = append(errs, err)
			logger.Error(err, "Error creating/updating ConfigMap", "name", cm.Name)
		} else {
			logger.Info("Reconciled ConfigMap", "name", cm.Name)
		}
	}
	for _, dep := range nfResource.GetDeployment(logger, nfDeploy, configInfo) {
		if dep == nil {
			continue
		}
		if dep.Namespace == "" {
			dep.Namespace = ns
		}
		existing := dep.DeepCopy()
		_, err := controllerutil.CreateOrUpdate(ctx, r.Client, existing, func() error {
			existing.Spec.Template.Spec.InitContainers = dep.Spec.Template.Spec.InitContainers
			existing.Spec.Template.Spec.Containers = dep.Spec.Template.Spec.Containers
			existing.Spec.Template.Spec.Volumes = dep.Spec.Template.Spec.Volumes
			existing.Spec.Template.Annotations = dep.Spec.Template.Annotations
			return nil
		})
		if err != nil {
			errs = append(errs, err)
			logger.Error(err, "Error creating/updating Deployment", "name", dep.Name)
		} else {
			logger.Info("Reconciled Deployment", "name", dep.Name)
		}
	}
	for _, svc := range GetServiceForNFDeployment(nfDeploy) {
		if svc.Namespace == "" {
			svc.Namespace = ns
		}
		existing := svc.DeepCopy()
		_, err := controllerutil.CreateOrUpdate(ctx, r.Client, existing, func() error {
			existing.Spec.Ports = svc.Spec.Ports
			existing.Spec.Selector = svc.Spec.Selector
			return nil
		})
		if err != nil {
			errs = append(errs, err)
			logger.Error(err, "Error creating/updating Service", "name", svc.Name)
		}
	}
	return errs
}

// DeleteAll deletes all Kubernetes resources generated by nfResource from the cluster.
func (r *RANDeploymentReconciler) DeleteAll(ctx context.Context, nfDeploy *workloadv1alpha1.NFDeployment, nfResource NfResource, configInfo *ConfigInfo) []error {
	logger := log.FromContext(ctx).WithValues("NFDeployment", types.NamespacedName{Namespace: nfDeploy.Namespace, Name: nfDeploy.Name})
	var errs []error
	ns := nfDeploy.Namespace

	for _, sa := range nfResource.GetServiceAccount() {
		if sa.Namespace == "" {
			sa.Namespace = ns
		}
		if err := r.Delete(ctx, sa); err != nil && !errors.IsNotFound(err) {
			errs = append(errs, err)
			logger.Error(err, "Error deleting ServiceAccount")
		}
	}
	for _, cm := range nfResource.GetConfigMap(logger, nfDeploy, configInfo) {
		if cm == nil {
			continue
		}
		if cm.Namespace == "" {
			cm.Namespace = ns
		}
		if err := r.Delete(ctx, cm); err != nil && !errors.IsNotFound(err) {
			errs = append(errs, err)
			logger.Error(err, "Error deleting ConfigMap", "name", cm.Name)
		}
	}
	for _, dep := range nfResource.GetDeployment(logger, nfDeploy, configInfo) {
		if dep == nil {
			continue
		}
		if dep.Namespace == "" {
			dep.Namespace = ns
		}
		if err := r.Delete(ctx, dep); err != nil && !errors.IsNotFound(err) {
			errs = append(errs, err)
			logger.Error(err, "Error deleting Deployment", "name", dep.Name)
		}
	}
	for _, svc := range GetServiceForNFDeployment(nfDeploy) {
		if svc.Namespace == "" {
			svc.Namespace = ns
		}
		if err := r.Delete(ctx, svc); err != nil && !errors.IsNotFound(err) {
			errs = append(errs, err)
			logger.Error(err, "Error deleting Service", "name", svc.Name)
		}
	}
	return errs
}

// GetConfigs reads NFDeployment.spec.parametersRefs → NFConfig.spec.configRefs (ObjectReferences)
// and fetches the actual CR objects from the cluster.
func (r *RANDeploymentReconciler) GetConfigs(ctx context.Context, nfDeploy *workloadv1alpha1.NFDeployment) (*ConfigInfo, error) {
	logger := log.FromContext(ctx).WithValues("NFDeployment", types.NamespacedName{Namespace: nfDeploy.Namespace, Name: nfDeploy.Name})
	configInfo := NewConfigInfo()

	for _, ref := range nfDeploy.Spec.ParametersRefs {
		logger.Info("Processing parametersRef", "apiVersion", ref.APIVersion, "kind", ref.Kind, "name", ref.Name)
		switch ref.APIVersion {
		case "workload.nephio.org/v1alpha1":
			if ref.Kind != "NFConfig" {
				logger.Info("Skipping non-NFConfig parametersRef", "kind", ref.Kind)
				continue
			}
			nfConfig := &workloadv1alpha1.NFConfig{}
			if err := r.Get(ctx, types.NamespacedName{Name: *ref.Name, Namespace: nfDeploy.Namespace}, nfConfig); err != nil {
				logger.Error(err, "Failed to get NFConfig")
				return configInfo, err
			}
			logger.Info("Got NFConfig", "name", nfConfig.Name, "configRefs", len(nfConfig.Spec.ConfigRefs))

			// Parse each configRef as ObjectReference and fetch the actual CR
			for _, rawRef := range nfConfig.Spec.ConfigRefs {
				kind, err := extractKindFromRaw(runtime.RawExtension{Raw: rawRef.Raw})
				if err != nil {
					logger.Error(err, "Cannot extract kind from configRef")
					return configInfo, err
				}
				name, err := extractNameFromRaw(runtime.RawExtension{Raw: rawRef.Raw})
				if err != nil {
					logger.Error(err, "Cannot extract name from configRef")
					return configInfo, err
				}
				logger.Info("Fetching config CR", "kind", kind, "name", name)

				switch kind {
				case "SrsRANCellConfig":
					cellCfg := &srsranov1alpha1.SrsRANCellConfig{}
					if err := r.Get(ctx, types.NamespacedName{Name: name, Namespace: nfDeploy.Namespace}, cellCfg); err != nil {
						logger.Error(err, "Failed to get SrsRANCellConfig", "name", name)
						return configInfo, err
					}
					configInfo.CellConfig = cellCfg
				case "PLMNConfig":
					plmnCfg := &srsranov1alpha1.PLMNConfig{}
					if err := r.Get(ctx, types.NamespacedName{Name: name, Namespace: nfDeploy.Namespace}, plmnCfg); err != nil {
						logger.Error(err, "Failed to get PLMNConfig", "name", name)
						return configInfo, err
					}
					configInfo.PLMNConfig = plmnCfg
				case "SrsRANConfig":
					srsranCfg := &srsranov1alpha1.SrsRANConfig{}
					if err := r.Get(ctx, types.NamespacedName{Name: name, Namespace: nfDeploy.Namespace}, srsranCfg); err != nil {
						logger.Error(err, "Failed to get SrsRANConfig", "name", name)
						return configInfo, err
					}
					configInfo.SrsRANConfig = srsranCfg
				default:
					logger.Info("Skipping unknown configRef kind", "kind", kind)
				}
			}

			if !configInfo.IsComplete() {
				missing := []string{}
				if configInfo.CellConfig == nil {
					missing = append(missing, "SrsRANCellConfig")
				}
				if configInfo.PLMNConfig == nil {
					missing = append(missing, "PLMNConfig")
				}
				if configInfo.SrsRANConfig == nil {
					missing = append(missing, "SrsRANConfig")
				}
				err := fmt.Errorf("mandatory config CRs not found: %v", missing)
				logger.Error(err, "NFConfig missing mandatory config references")
				return configInfo, err
			}
		default:
			logger.Info("Skipping unsupported parametersRef apiVersion", "apiVersion", ref.APIVersion)
		}
	}
	return configInfo, nil
}

// updateStatusIfRequired updates NFDeployment.status.conditions only when
// the condition actually changed, to avoid spurious updates.
// Also ensures observedGeneration is set correctly for kstatus compatibility.
func (r *RANDeploymentReconciler) updateStatusIfRequired(ctx context.Context, nfDeploy *workloadv1alpha1.NFDeployment, cur metav1.Condition) error {
	// Check if observedGeneration needs update
	needsGenerationUpdate := nfDeploy.Status.ObservedGeneration != int32(nfDeploy.Generation)

	for i, old := range nfDeploy.Status.Conditions {
		if old.Type == cur.Type {
			if old.Reason == cur.Reason && old.Message == cur.Message && old.Status == cur.Status {
				// Condition hasn't changed, only update if observedGeneration needs updating
				if needsGenerationUpdate {
					nfDeploy.Status.ObservedGeneration = int32(nfDeploy.Generation)
					return r.Status().Update(ctx, nfDeploy)
				}
				return nil // No update needed
			}
			// Condition changed, update it
			nfDeploy.Status.Conditions[i] = cur
			nfDeploy.Status.ObservedGeneration = int32(nfDeploy.Generation)
			return r.Status().Update(ctx, nfDeploy)
		}
	}
	// New condition, append it
	nfDeploy.Status.Conditions = append(nfDeploy.Status.Conditions, cur)
	nfDeploy.Status.ObservedGeneration = int32(nfDeploy.Generation)
	return r.Status().Update(ctx, nfDeploy)
}

// +kubebuilder:rbac:groups=workload.nephio.org,resources=nfdeployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=workload.nephio.org,resources=nfdeployments/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=workload.nephio.org,resources=nfdeployments/finalizers,verbs=update
// +kubebuilder:rbac:groups=workload.nephio.org,resources=nfconfigs,verbs=get;list;watch
// +kubebuilder:rbac:groups=workload.nephio.org,resources=srsrancellconfigs;plmnconfigs;srsranconfigs,verbs=get;list;watch
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups="",resources=configmaps;serviceaccounts;services,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups="",resources=pods,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch
// +kubebuilder:rbac:groups=k8s.cni.cncf.io,resources=network-attachment-definitions,verbs=get;list;watch;create;update;patch;delete

// Reconcile is the main control loop.
func (r *RANDeploymentReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx).WithValues("NFDeployment", req.NamespacedName)
	logger.Info("Reconcile called")

	// 1. Fetch the NFDeployment.
	instance := &workloadv1alpha1.NFDeployment{}
	if err := r.Get(ctx, req.NamespacedName, instance); err != nil {
		if errors.IsNotFound(err) {
			logger.Info("NFDeployment not found; object was deleted")
			return ctrl.Result{}, nil
		}
		logger.Error(err, "Failed to get NFDeployment")
		return ctrl.Result{}, err
	}

	// 2. Filter by provider.
	if !slices.Contains(GetSupportedProviders(), instance.Spec.Provider) {
		logger.Info("Ignoring NFDeployment with unsupported provider", "provider", instance.Spec.Provider)
		return ctrl.Result{}, nil
	}
	logger.Info("Processing NFDeployment", "provider", instance.Spec.Provider)

	// 3. Read configuration from parametersRefs chain.
	configInfo, err := r.GetConfigs(ctx, instance)
	if err != nil {
		logger.Error(err, "Failed to get required ConfigInfo; requeueing")
		_ = r.updateStatusIfRequired(ctx, instance, metav1.Condition{
			Type:               "invalidConfigInfo",
			LastTransitionTime: metav1.Time{Time: time.Now()},
			Status:             metav1.ConditionFalse,
			Reason:             "invalidConfigInfo",
			Message:            fmt.Sprintf("Failed to get ConfigInfo: %v", err),
		})
		return ctrl.Result{RequeueAfter: 15 * time.Second}, err
	}

	// 4. Check if all required interfaces are present (IPs injected by nfdeploy-fn).
	// If not yet present, requeue without error (IPAM pipeline still running).
	for _, ifName := range []string{"n2", "n3", "e1", "f1c", "f1u"} {
		if _, ipErr := GetFirstInterfaceConfigIPv4(instance.Spec.Interfaces, ifName); ipErr != nil {
			logger.Info("Interface IP not yet available; requeueing", "interface", ifName)
			return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
		}
	}

	const finalizerName = "srsran.nephio.org/finalizer"
	gnbResource := GnbResources{}

	if instance.DeletionTimestamp.IsZero() {
		// Object is not being deleted – always reconcile resources.
		errList := r.CreateAll(ctx, instance, gnbResource, configInfo)

		var cond metav1.Condition
		if len(errList) == 0 {
			cond = metav1.Condition{
				Type:               "resourceCreation",
				LastTransitionTime: metav1.Time{Time: time.Now()},
				Status:             metav1.ConditionTrue,
				Reason:             "resourceCreation",
				Message:            "All srsRAN gNB resources reconciled successfully",
			}
		} else {
			msgs := ""
			for _, e := range errList {
				msgs += e.Error() + "; "
			}
			cond = metav1.Condition{
				Type:               "resourceCreation",
				LastTransitionTime: metav1.Time{Time: time.Now()},
				Status:             metav1.ConditionFalse,
				Reason:             "resourceCreation",
				Message:            msgs,
			}
		}
		if err := r.updateStatusIfRequired(ctx, instance, cond); err != nil {
			logger.Error(err, "Failed to update status after resource reconciliation")
		}

		// Set Ready condition for ConfigSync compatibility
		var readyCond metav1.Condition
		if len(errList) == 0 {
			readyCond = metav1.Condition{
				Type:               "Ready",
				LastTransitionTime: metav1.Time{Time: time.Now()},
				Status:             metav1.ConditionTrue,
				Reason:             "Reconciled",
				Message:            "NFDeployment reconciled successfully",
			}
		} else {
			readyCond = metav1.Condition{
				Type:               "Ready",
				LastTransitionTime: metav1.Time{Time: time.Now()},
				Status:             metav1.ConditionFalse,
				Reason:             "ReconcileFailed",
				Message:            "NFDeployment reconciliation failed",
			}
		}
		if err := r.updateStatusIfRequired(ctx, instance, readyCond); err != nil {
			logger.Error(err, "Failed to update Ready status")
		}

		// Ensure finalizer is present so cleanup runs on deletion.
		if !controllerutil.ContainsFinalizer(instance, finalizerName) {
			controllerutil.AddFinalizer(instance, finalizerName)
			if err := r.Update(ctx, instance); err != nil {
				return ctrl.Result{}, err
			}
		}
	} else {
		// Object is being deleted.
		if controllerutil.ContainsFinalizer(instance, finalizerName) {
			logger.Info("Deleting srsRAN gNB resources")
			errList := r.DeleteAll(ctx, instance, gnbResource, configInfo)

			var cond metav1.Condition
			if len(errList) == 0 {
				cond = metav1.Condition{
					Type:               "resourceDeletion",
					LastTransitionTime: metav1.Time{Time: time.Now()},
					Status:             metav1.ConditionTrue,
					Reason:             "resourceDeletion",
					Message:            "All srsRAN gNB resources deleted successfully",
				}
			} else {
				msgs := ""
				for _, e := range errList {
					msgs += e.Error() + "; "
				}
				cond = metav1.Condition{
					Type:               "resourceDeletion",
					LastTransitionTime: metav1.Time{Time: time.Now()},
					Status:             metav1.ConditionFalse,
					Reason:             "resourceDeletion",
					Message:            msgs,
				}
			}
			if err := r.updateStatusIfRequired(ctx, instance, cond); err != nil {
				logger.Error(err, "Failed to update status after resource deletion")
			}

			controllerutil.RemoveFinalizer(instance, finalizerName)
			if err := r.Update(ctx, instance); err != nil {
				return ctrl.Result{}, err
			}
		}
		return ctrl.Result{}, nil
	}

	return ctrl.Result{}, nil
}

// findNFDeploymentsForConfig returns reconcile requests for all NFDeployments
// that reference the changed config CR via NFConfig.
func (r *RANDeploymentReconciler) findNFDeploymentsForConfig(ctx context.Context, obj client.Object) []reconcile.Request {
	// Determine the Kind from the concrete type, since obj.GetObjectKind() often
	// returns empty GVK for objects read from the cache in controller-runtime.
	var objKind string
	switch obj.(type) {
	case *srsranov1alpha1.SrsRANCellConfig:
		objKind = "SrsRANCellConfig"
	case *srsranov1alpha1.PLMNConfig:
		objKind = "PLMNConfig"
	case *srsranov1alpha1.SrsRANConfig:
		objKind = "SrsRANConfig"
	default:
		objKind = obj.GetObjectKind().GroupVersionKind().Kind
	}

	logger := log.FromContext(ctx).WithValues("configKind", objKind, "configName", obj.GetName())
	logger.Info("Config change detected, looking for affected NFDeployments")

	// List all NFDeployments in the same namespace
	nfDeployList := &workloadv1alpha1.NFDeploymentList{}
	if err := r.List(ctx, nfDeployList, client.InNamespace(obj.GetNamespace())); err != nil {
		logger.Error(err, "Failed to list NFDeployments")
		return nil
	}

	var requests []reconcile.Request
	for _, nfDeploy := range nfDeployList.Items {
		// Only process NFDeployments with supported providers
		if !slices.Contains(GetSupportedProviders(), nfDeploy.Spec.Provider) {
			continue
		}

		// Check if this NFDeployment references an NFConfig that references the changed config
		for _, ref := range nfDeploy.Spec.ParametersRefs {
			if ref.APIVersion == "workload.nephio.org/v1alpha1" && ref.Kind == "NFConfig" && ref.Name != nil {
				nfConfig := &workloadv1alpha1.NFConfig{}
				if err := r.Get(ctx, types.NamespacedName{Name: *ref.Name, Namespace: nfDeploy.Namespace}, nfConfig); err != nil {
					continue
				}
				// Check if this NFConfig references the changed config CR
				for _, configRef := range nfConfig.Spec.ConfigRefs {
					kind, _ := extractKindFromRaw(runtime.RawExtension{Raw: configRef.Raw})
					name, _ := extractNameFromRaw(runtime.RawExtension{Raw: configRef.Raw})
					if kind == objKind && name == obj.GetName() {
						logger.Info("Enqueueing NFDeployment for config change", "nfDeployment", nfDeploy.Name)
						requests = append(requests, reconcile.Request{
							NamespacedName: types.NamespacedName{
								Name:      nfDeploy.Name,
								Namespace: nfDeploy.Namespace,
							},
						})
						break
					}
				}
			}
		}
	}
	return requests
}

// SetupWithManager registers the controller with the Manager.
func (r *RANDeploymentReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&workloadv1alpha1.NFDeployment{}).
		Watches(&srsranov1alpha1.SrsRANCellConfig{},
			handler.EnqueueRequestsFromMapFunc(r.findNFDeploymentsForConfig)).
		Watches(&srsranov1alpha1.PLMNConfig{},
			handler.EnqueueRequestsFromMapFunc(r.findNFDeploymentsForConfig)).
		Watches(&srsranov1alpha1.SrsRANConfig{},
			handler.EnqueueRequestsFromMapFunc(r.findNFDeploymentsForConfig)).
		Complete(r)
}

