/*
Copyright 2024 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"bytes"
	"fmt"
	"text/template"

	srsranov1alpha1 "workload.nephio.org/srsran_operator/api/v1alpha1"
)

// ─────────────────────────────────────────────────────────────────────────────
// QoS ConfigMap template
//
// Six 5QI profiles are supported (ETSI TS 23.501 Table 5.7.4-1):
//
//	5QI | Slice | PDCP DiscardTimer | RLC Mode | Scheduler priority
//	----+-------+-------------------+----------+--------------------
//	9   | eMBB  | 300 ms            | AM       | 20  (default bearer)
//	7   | eMBB  | 100 ms            | UM       | 60
//	10  | eMBB  | 100 ms            | UM       | 50
//	82  | URLLC | 100 ms            | AM       | 160
//	84  | URLLC | 10 ms             | UM       | 230
//	85  | URLLC | 10 ms             | UM       | 250 (mission-critical)
// ─────────────────────────────────────────────────────────────────────────────

// qosProfile holds the per-5QI radio parameters fed into the QoS template.
type qosProfile struct {
	FiveQI             int
	SliceType          srsranov1alpha1.SliceType
	PDCPDiscardTimerMs int    // 0 = infinity
	RLCMode            string // "AM" or "UM"
	SchedulerPriority  int    // 0–255
	PFfairnessCoeff    float64
	PDBEnabled         bool
	GBREnabled         bool
}

// fiveQIProfiles maps 5QI → qosProfile.
var fiveQIProfiles = map[int]qosProfile{
	9:  {9, srsranov1alpha1.SliceTypeMBB, 300, "AM", 20, 5.0, false, false},
	7:  {7, srsranov1alpha1.SliceTypeMBB, 100, "UM", 60, 3.0, false, false},
	10: {10, srsranov1alpha1.SliceTypeMBB, 100, "UM", 50, 3.5, false, false},
	82: {82, srsranov1alpha1.SliceTypeURLLC, 100, "AM", 160, 2.0, false, true},
	84: {84, srsranov1alpha1.SliceTypeURLLC, 10, "UM", 230, 1.0, true, true},
	85: {85, srsranov1alpha1.SliceTypeURLLC, 10, "UM", 250, 1.0, true, true},
}

const qosTemplateSource = `# Auto-generated by srsran-operator – DO NOT EDIT
# 5QI: {{ .FiveQI }} | Slice: {{ .SliceType }}
qos:
  five_qi: {{ .FiveQI }}
  slice_type: "{{ .SliceType }}"

  pdcp:
    discard_timer_ms: {{ .PDCPDiscardTimerMs }}  # 0 = infinity (never discard)
    rlc_mode: "{{ .RLCMode }}"                   # AM = acknowledged, UM = unacknowledged

  scheduler:
    priority: {{ .SchedulerPriority }}           # 0-255; higher value = scheduled first
    pf_fairness_coeff: {{ .PFfairnessCoeff }}    # Proportional Fair coefficient
    pdb_enabled: {{ .PDBEnabled }}               # Packet Delay Budget enforcement
    gbr_enabled: {{ .GBREnabled }}               # Guaranteed Bit Rate scheduling
{{- if eq .RLCMode "UM" }}

  # Latency-optimised settings for UM (Unacknowledged Mode).
  rlc:
    sn_field_length: 6
    t_reassembly_ms: 40
{{- else }}

  # Reliability-optimised settings for AM (Acknowledged Mode).
  rlc:
    sn_field_length: 18
    t_poll_retransmit_ms: 45
    t_reassembly_ms: 35
    t_status_prohibit_ms: 0
{{- end }}
`

var qosTemplate = template.Must(template.New("qos").Parse(qosTemplateSource))

// renderQoSConfigMap generates qos.yaml for the given SliceIntent.
// Unknown 5QIs fall back to the eMBB / 5QI=9 defaults.
func renderQoSConfigMap(intent srsranov1alpha1.SliceIntent) (string, error) {
	profile, ok := fiveQIProfiles[intent.FiveQI]
	if !ok {
		profile = fiveQIProfiles[9]
		profile.FiveQI = intent.FiveQI
	}
	var buf bytes.Buffer
	if err := qosTemplate.Execute(&buf, profile); err != nil {
		return "", fmt.Errorf("renderQoSConfigMap: %w", err)
	}
	return buf.String(), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// CU-CP configuration template
// ─────────────────────────────────────────────────────────────────────────────

// CUCPConfigValues holds the dynamic values injected into the CU-CP config.
type CUCPConfigValues struct {
	// N2BindAddr is the NGAP bind address on the N2 interface (CU-CP ↔ AMF).
	N2BindAddr string
	// AMFAddr is the AMF NGAP address (IP or hostname).
	AMFAddr string
	// E1BindAddr is the E1AP server bind address (CU-CP ↔ CU-UP).
	E1BindAddr string
	// F1CBindAddr is the F1-AP server bind address (CU-CP ↔ DU).
	F1CBindAddr string
	// PLMN is the 5-digit PLMN string (e.g. "20893").
	PLMN string
	// TAC is the Tracking Area Code.
	TAC uint32
	// Slices is the list of S-NSSAI slices advertised in supported_tracking_areas.
	Slices []srsranov1alpha1.SliceInfo
	// InactivityTimer in seconds (default 7200).
	InactivityTimer int
	// RequestPDUSessionTimeout in seconds (default 20).
	RequestPDUSessionTimeout int
}

const cucpConfigTemplateSource = `# Auto-generated by srsran-operator – DO NOT EDIT
# CU-CP: N2={{ .N2BindAddr }} E1={{ .E1BindAddr }} F1C={{ .F1CBindAddr }}

cu_cp:
  request_pdu_session_timeout: {{ .RequestPDUSessionTimeout }}
  inactivity_timer: {{ .InactivityTimer }}
  amf:
    addr: {{ .AMFAddr }}
    port: 38412
    bind_addr: {{ .N2BindAddr }}
    supported_tracking_areas:
    - tac: {{ .TAC }}
      plmn_list:
      - plmn: "{{ .PLMN }}"
        tai_slice_support_list:
        {{- range .Slices }}
        - sst: {{ .SST }}
          {{- if .SD }}
          sd: "{{ .SD }}"
          {{- end }}
        {{- end }}
  e1ap:
    bind_addr: {{ .E1BindAddr }}
  f1ap:
    bind_addr: {{ .F1CBindAddr }}

log:
  filename: /tmp/logs/cu_cp.log
  all_level: info

pcap:
  ngap_enable: false
  e1ap_enable: false
  f1ap_enable: false

expert_execution:
  threads:
    main_pool:
      backoff_period: 1000
`

var cucpConfigTemplate = template.Must(template.New("cu-cp-config").Parse(cucpConfigTemplateSource))

// renderCUCPConfig renders the srsRAN CU-CP YAML configuration.
func renderCUCPConfig(v CUCPConfigValues) (string, error) {
	var buf bytes.Buffer
	if err := cucpConfigTemplate.Execute(&buf, v); err != nil {
		return "", fmt.Errorf("renderCUCPConfig: %w", err)
	}
	return buf.String(), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// CU-UP configuration template
// ─────────────────────────────────────────────────────────────────────────────

// CUUPConfigValues holds the dynamic values injected into the CU-UP config.
type CUUPConfigValues struct {
	// E1CUCPAddr is the CU-CP Service address for the E1AP client connection.
	E1CUCPAddr string
	// E1BindAddr is the E1AP bind address on the E1 interface.
	E1BindAddr string
	// N3BindAddr is the GTP-U bind address on the N3 interface (CU-UP ↔ UPF).
	N3BindAddr string
	// F1UBindAddr is the F1-U GTP-U bind address (CU-UP ↔ DU).
	F1UBindAddr string
}

const cuupConfigTemplateSource = `# Auto-generated by srsran-operator – DO NOT EDIT
# CU-UP: E1CUCPAddr={{ .E1CUCPAddr }} E1={{ .E1BindAddr }} N3={{ .N3BindAddr }} F1U={{ .F1UBindAddr }}

cu_up:
  e1ap:
    cu_cp_addr: {{ .E1CUCPAddr }}
    bind_addr: {{ .E1BindAddr }}
  ngu:
    socket:
    - bind_addr: {{ .N3BindAddr }}
  f1u:
    socket:
    - bind_addr: {{ .F1UBindAddr }}

log:
  filename: /tmp/logs/cu_up.log
  all_level: info

pcap:
  e1ap_enable: false
  f1u_enable: false
  n3_enable: false

expert_execution:
  threads:
    main_pool:
      backoff_period: 1000
`

var cuupConfigTemplate = template.Must(template.New("cu-up-config").Parse(cuupConfigTemplateSource))

// renderCUUPConfig renders the srsRAN CU-UP YAML configuration.
func renderCUUPConfig(v CUUPConfigValues) (string, error) {
	var buf bytes.Buffer
	if err := cuupConfigTemplate.Execute(&buf, v); err != nil {
		return "", fmt.Errorf("renderCUUPConfig: %w", err)
	}
	return buf.String(), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// DU configuration template
// ─────────────────────────────────────────────────────────────────────────────

// DUConfigValues holds the dynamic values injected into the DU config template.
type DUConfigValues struct {
	// F1CCUCPAddr is the CU-CP Service DNS for F1-AP client connection.
	F1CCUCPAddr string
	// F1CBindAddr is the DU F1-AP (control) bind address.
	F1CBindAddr string
	// F1UBindAddr is the DU F1-U (user plane) bind address.
	F1UBindAddr string
	// ZMQTxAddr is the address the DU ZMQ TX socket connects to (UE's IP).
	ZMQTxAddr string
	// ZMQTxPort is the ZMQ TX port (on ZMQTxAddr, i.e. UE side).
	ZMQTxPort int
	// ZMQRxAddr is the address the DU ZMQ RX socket binds to (DU's own F1U IP).
	ZMQRxAddr string
	// ZMQRxPort is the ZMQ RX port (on ZMQRxAddr, i.e. DU side).
	ZMQRxPort int
	// SRate is the RF sample rate in MHz (e.g. "23.04").
	SRate string
	// TxGain is the RF transmit gain.
	TxGain uint32
	// RxGain is the RF receive gain.
	RxGain uint32
	// DlArfcn is the downlink ARFCN.
	DlArfcn uint32
	// Band is the NR operating band number.
	Band uint32
	// ChannelBandwidthMHz is the channel bandwidth in MHz.
	ChannelBandwidthMHz uint32
	// CommonScs is the subcarrier spacing in kHz.
	CommonScs uint32
	// PLMN is the 5-digit PLMN string.
	PLMN string
	// TAC is the Tracking Area Code.
	TAC uint32
	// PCI is the Physical Cell ID.
	PCI uint32
	// PDCCH holds the PDCCH configuration values.
	PDCCH srsranov1alpha1.SrsRANPDCCHConfig
	// PRACH holds the PRACH configuration values.
	PRACH srsranov1alpha1.SrsRANPRACHConfig
	// PDSCHMcsTable is the MCS table for PDSCH ("qam64" or "qam256").
	PDSCHMcsTable string
	// PUSCHMcsTable is the MCS table for PUSCH ("qam64" or "qam256").
	PUSCHMcsTable string
	// Slicing holds the network slice configurations.
	Slicing []srsranov1alpha1.SrsRANSliceConfig
}

const duConfigTemplateSource = `# Auto-generated by srsran-operator – DO NOT EDIT
# DU: F1CCUCPAddr={{ .F1CCUCPAddr }} F1C={{ .F1CBindAddr }} F1U={{ .F1UBindAddr }}

f1ap:
  cu_cp_addr: {{ .F1CCUCPAddr }}
  bind_addr: {{ .F1CBindAddr }}

f1u:
  socket:
  - bind_addr: {{ .F1UBindAddr }}

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://{{ .ZMQTxAddr }}:{{ .ZMQTxPort }},rx_port=tcp://{{ .ZMQRxAddr }}:{{ .ZMQRxPort }},base_srate={{ .SRate }}e6
  srate: {{ .SRate }}
  tx_gain: {{ .TxGain }}
  rx_gain: {{ .RxGain }}

cell_cfg:
  dl_arfcn: {{ .DlArfcn }}
  band: {{ .Band }}
  channel_bandwidth_MHz: {{ .ChannelBandwidthMHz }}
  common_scs: {{ .CommonScs }}
  plmn: "{{ .PLMN }}"
  tac: {{ .TAC }}
  pci: {{ .PCI }}
  pdcch:
    common:
      ss0_index: {{ .PDCCH.SS0Index }}
      coreset0_index: {{ .PDCCH.Coreset0Index }}
    dedicated:
      ss2_type: {{ .PDCCH.SS2Type }}
      dci_format_0_1_and_1_1: {{ .PDCCH.DCIFormat01and11 }}
  prach:
    prach_config_index: {{ .PRACH.PrachConfigIndex }}
  pdsch:
    mcs_table: {{ .PDSCHMcsTable }}
  pusch:
    mcs_table: {{ .PUSCHMcsTable }}
{{- if .Slicing }}
  slicing:
{{- range .Slicing }}
    - sst: {{ .SST }}
      sd: {{ .SD }}
      sched_cfg:
        min_prb_policy_ratio: {{ .SchedCfg.MinPrbPolicyRatio }}
        max_prb_policy_ratio: {{ .SchedCfg.MaxPrbPolicyRatio }}
        priority: {{ .SchedCfg.Priority }}
{{- end }}
{{- end }}

log:
  filename: /tmp/logs/du.log
  all_level: info

pcap:
  mac_enable: false
  f1ap_enable: false
  f1u_enable: false

expert_execution:
  threads:
    main_pool:
      backoff_period: 1000
`

var duConfigTemplate = template.Must(template.New("du-config").Parse(duConfigTemplateSource))

// renderDUConfig renders the srsRAN DU YAML configuration.
func renderDUConfig(v DUConfigValues) (string, error) {
	var buf bytes.Buffer
	if err := duConfigTemplate.Execute(&buf, v); err != nil {
		return "", fmt.Errorf("renderDUConfig: %w", err)
	}
	return buf.String(), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// srsUE configuration template (INI format)
// ─────────────────────────────────────────────────────────────────────────────

// UEConfigValues holds the dynamic values injected into the srsUE config.
type UEConfigValues struct {
	// ZMQTarget is the IP/hostname of the DU or RadioBreaker.
	ZMQTarget string
	// ZMQTXPort is the UE TX → DU/RB RX port.
	ZMQTXPort int
	// ZMQRXPort is the UE RX ← DU/RB TX port.
	ZMQRXPort int
	// PLMN is the 5-digit PLMN (must match gNB cell_cfg.plmn).
	PLMN string
	// FiveQI is stored for traceability.
	FiveQI int
}

const ueConfigTemplateSource = `# Auto-generated by srsran-operator – DO NOT EDIT
# ZMQ target: {{ .ZMQTarget }}:{{ .ZMQTXPort }}/{{ .ZMQRXPort }}

[rf]
freq_offset = 0
tx_gain     = 80
rx_gain     = 40
srate       = 23.04e6
device_name = zmq
device_args = tx_port=tcp://{{ .ZMQTarget }}:{{ .ZMQTXPort }},rx_port=tcp://{{ .ZMQTarget }}:{{ .ZMQRXPort }},base_srate=23.04e6

[rat.eutra]
dl_earfcn = 2850
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1

[usim]
mode  = soft
algo  = milenage
opc   = 63BFA50EE6523365FF14C1F45F88737D
k     = 00112233445566778899AABBCCDDEEFF
imsi  = 208930000000001
imei  = 356938035643803

[rrc]
release = 15
ue_category = 4

[nas]
apn = internet
apn_protocol = ipv4

[log]
filename    = /tmp/ue.log
all_level   = info

[pcap]
enable    = false
filename  = /tmp/ue.pcap
`

var ueConfigTemplate = template.Must(template.New("ue-config").Parse(ueConfigTemplateSource))

// renderUEConfig renders the srsUE INI-style configuration.
func renderUEConfig(v UEConfigValues) (string, error) {
	var buf bytes.Buffer
	if err := ueConfigTemplate.Execute(&buf, v); err != nil {
		return "", fmt.Errorf("renderUEConfig: %w", err)
	}
	return buf.String(), nil
}
