//go:build !ignore_autogenerated

/*
Copyright 2024 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AchievedTargets) DeepCopyInto(out *AchievedTargets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AchievedTargets.
func (in *AchievedTargets) DeepCopy() *AchievedTargets {
	if in == nil {
		return nil
	}
	out := new(AchievedTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreDomainParams) DeepCopyInto(out *CoreDomainParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreDomainParams.
func (in *CoreDomainParams) DeepCopy() *CoreDomainParams {
	if in == nil {
		return nil
	}
	out := new(CoreDomainParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainFulfillmentStatus) DeepCopyInto(out *DomainFulfillmentStatus) {
	*out = *in
	if in.CoreDomain != nil {
		in, out := &in.CoreDomain, &out.CoreDomain
		*out = new(DomainStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RANDomain != nil {
		in, out := &in.RANDomain, &out.RANDomain
		*out = new(DomainStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainFulfillmentStatus.
func (in *DomainFulfillmentStatus) DeepCopy() *DomainFulfillmentStatus {
	if in == nil {
		return nil
	}
	out := new(DomainFulfillmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainStatus) DeepCopyInto(out *DomainStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainStatus.
func (in *DomainStatus) DeepCopy() *DomainStatus {
	if in == nil {
		return nil
	}
	out := new(DomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2EQoSIntent) DeepCopyInto(out *E2EQoSIntent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2EQoSIntent.
func (in *E2EQoSIntent) DeepCopy() *E2EQoSIntent {
	if in == nil {
		return nil
	}
	out := new(E2EQoSIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *E2EQoSIntent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2EQoSIntentList) DeepCopyInto(out *E2EQoSIntentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]E2EQoSIntent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2EQoSIntentList.
func (in *E2EQoSIntentList) DeepCopy() *E2EQoSIntentList {
	if in == nil {
		return nil
	}
	out := new(E2EQoSIntentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *E2EQoSIntentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2EQoSIntentSpec) DeepCopyInto(out *E2EQoSIntentSpec) {
	*out = *in
	if in.IntentGroups != nil {
		in, out := &in.IntentGroups, &out.IntentGroups
		*out = make([]IntentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2EQoSIntentSpec.
func (in *E2EQoSIntentSpec) DeepCopy() *E2EQoSIntentSpec {
	if in == nil {
		return nil
	}
	out := new(E2EQoSIntentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2EQoSIntentStatus) DeepCopyInto(out *E2EQoSIntentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IntentGroupStatuses != nil {
		in, out := &in.IntentGroupStatuses, &out.IntentGroupStatuses
		*out = make([]IntentGroupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2EQoSIntentStatus.
func (in *E2EQoSIntentStatus) DeepCopy() *E2EQoSIntentStatus {
	if in == nil {
		return nil
	}
	out := new(E2EQoSIntentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentContexts) DeepCopyInto(out *IntentContexts) {
	*out = *in
	if in.TargetUEs != nil {
		in, out := &in.TargetUEs, &out.TargetUEs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentContexts.
func (in *IntentContexts) DeepCopy() *IntentContexts {
	if in == nil {
		return nil
	}
	out := new(IntentContexts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentExpectations) DeepCopyInto(out *IntentExpectations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentExpectations.
func (in *IntentExpectations) DeepCopy() *IntentExpectations {
	if in == nil {
		return nil
	}
	out := new(IntentExpectations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentGroup) DeepCopyInto(out *IntentGroup) {
	*out = *in
	in.Contexts.DeepCopyInto(&out.Contexts)
	out.Expectations = in.Expectations
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentGroup.
func (in *IntentGroup) DeepCopy() *IntentGroup {
	if in == nil {
		return nil
	}
	out := new(IntentGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentGroupStatus) DeepCopyInto(out *IntentGroupStatus) {
	*out = *in
	if in.TranslatedParams != nil {
		in, out := &in.TranslatedParams, &out.TranslatedParams
		*out = new(TranslatedParams)
		(*in).DeepCopyInto(*out)
	}
	if in.AchievedTargets != nil {
		in, out := &in.AchievedTargets, &out.AchievedTargets
		*out = new(AchievedTargets)
		**out = **in
	}
	if in.DomainStatus != nil {
		in, out := &in.DomainStatus, &out.DomainStatus
		*out = new(DomainFulfillmentStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentGroupStatus.
func (in *IntentGroupStatus) DeepCopy() *IntentGroupStatus {
	if in == nil {
		return nil
	}
	out := new(IntentGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RANDomainParams) DeepCopyInto(out *RANDomainParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RANDomainParams.
func (in *RANDomainParams) DeepCopy() *RANDomainParams {
	if in == nil {
		return nil
	}
	out := new(RANDomainParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TranslatedParams) DeepCopyInto(out *TranslatedParams) {
	*out = *in
	if in.CoreParams != nil {
		in, out := &in.CoreParams, &out.CoreParams
		*out = new(CoreDomainParams)
		**out = **in
	}
	if in.RANParams != nil {
		in, out := &in.RANParams, &out.RANParams
		*out = new(RANDomainParams)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TranslatedParams.
func (in *TranslatedParams) DeepCopy() *TranslatedParams {
	if in == nil {
		return nil
	}
	out := new(TranslatedParams)
	in.DeepCopyInto(out)
	return out
}
