apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n3
  annotations:
    # N3 carries GTP-U user-plane traffic between CU-UP and the UPF.
    nephio.org/network-name: n3
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.gnb-example
    specializer.nephio.org/namespace: example
spec:
  networkInstance:
    name: vpc-ran
  cniType: macvlan
  attachmentType: vlan
