apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # Package name / namespace used by apply-replacements-namespace.yaml
  # to set metadata.namespace on all package resources.
  name: example
