//go:build !ignore_autogenerated

/*
Copyright 2024 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLMNConfig) DeepCopyInto(out *PLMNConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLMNConfig.
func (in *PLMNConfig) DeepCopy() *PLMNConfig {
	if in == nil {
		return nil
	}
	out := new(PLMNConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PLMNConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLMNConfigList) DeepCopyInto(out *PLMNConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PLMNConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLMNConfigList.
func (in *PLMNConfigList) DeepCopy() *PLMNConfigList {
	if in == nil {
		return nil
	}
	out := new(PLMNConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PLMNConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLMNConfigSpec) DeepCopyInto(out *PLMNConfigSpec) {
	*out = *in
	if in.Slices != nil {
		in, out := &in.Slices, &out.Slices
		*out = make([]SliceInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLMNConfigSpec.
func (in *PLMNConfigSpec) DeepCopy() *PLMNConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PLMNConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PLMNConfigStatus) DeepCopyInto(out *PLMNConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PLMNConfigStatus.
func (in *PLMNConfigStatus) DeepCopy() *PLMNConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PLMNConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceInfo) DeepCopyInto(out *SliceInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceInfo.
func (in *SliceInfo) DeepCopy() *SliceInfo {
	if in == nil {
		return nil
	}
	out := new(SliceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceIntent) DeepCopyInto(out *SliceIntent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceIntent.
func (in *SliceIntent) DeepCopy() *SliceIntent {
	if in == nil {
		return nil
	}
	out := new(SliceIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANCellConfig) DeepCopyInto(out *SrsRANCellConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANCellConfig.
func (in *SrsRANCellConfig) DeepCopy() *SrsRANCellConfig {
	if in == nil {
		return nil
	}
	out := new(SrsRANCellConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SrsRANCellConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANCellConfigList) DeepCopyInto(out *SrsRANCellConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SrsRANCellConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANCellConfigList.
func (in *SrsRANCellConfigList) DeepCopy() *SrsRANCellConfigList {
	if in == nil {
		return nil
	}
	out := new(SrsRANCellConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SrsRANCellConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANCellConfigSpec) DeepCopyInto(out *SrsRANCellConfigSpec) {
	*out = *in
	out.PDCCH = in.PDCCH
	out.PRACH = in.PRACH
	if in.Slicing != nil {
		in, out := &in.Slicing, &out.Slicing
		*out = make([]SrsRANSliceConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANCellConfigSpec.
func (in *SrsRANCellConfigSpec) DeepCopy() *SrsRANCellConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SrsRANCellConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANCellConfigStatus) DeepCopyInto(out *SrsRANCellConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANCellConfigStatus.
func (in *SrsRANCellConfigStatus) DeepCopy() *SrsRANCellConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SrsRANCellConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANConfig) DeepCopyInto(out *SrsRANConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANConfig.
func (in *SrsRANConfig) DeepCopy() *SrsRANConfig {
	if in == nil {
		return nil
	}
	out := new(SrsRANConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SrsRANConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANConfigList) DeepCopyInto(out *SrsRANConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SrsRANConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANConfigList.
func (in *SrsRANConfigList) DeepCopy() *SrsRANConfigList {
	if in == nil {
		return nil
	}
	out := new(SrsRANConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SrsRANConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANConfigSpec) DeepCopyInto(out *SrsRANConfigSpec) {
	*out = *in
	out.SliceIntent = in.SliceIntent
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANConfigSpec.
func (in *SrsRANConfigSpec) DeepCopy() *SrsRANConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SrsRANConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANConfigStatus) DeepCopyInto(out *SrsRANConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANConfigStatus.
func (in *SrsRANConfigStatus) DeepCopy() *SrsRANConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SrsRANConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANPDCCHConfig) DeepCopyInto(out *SrsRANPDCCHConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANPDCCHConfig.
func (in *SrsRANPDCCHConfig) DeepCopy() *SrsRANPDCCHConfig {
	if in == nil {
		return nil
	}
	out := new(SrsRANPDCCHConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANPRACHConfig) DeepCopyInto(out *SrsRANPRACHConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANPRACHConfig.
func (in *SrsRANPRACHConfig) DeepCopy() *SrsRANPRACHConfig {
	if in == nil {
		return nil
	}
	out := new(SrsRANPRACHConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANSliceConfig) DeepCopyInto(out *SrsRANSliceConfig) {
	*out = *in
	out.SchedCfg = in.SchedCfg
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANSliceConfig.
func (in *SrsRANSliceConfig) DeepCopy() *SrsRANSliceConfig {
	if in == nil {
		return nil
	}
	out := new(SrsRANSliceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SrsRANSliceSchedConfig) DeepCopyInto(out *SrsRANSliceSchedConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SrsRANSliceSchedConfig.
func (in *SrsRANSliceSchedConfig) DeepCopy() *SrsRANSliceSchedConfig {
	if in == nil {
		return nil
	}
	out := new(SrsRANSliceSchedConfig)
	in.DeepCopyInto(out)
	return out
}
